// mockArtists.js

const mockArtists = [
    {
      id: 1,
      name: "Aria Harmony",
      category: "Singer, Songwriter",
      genre: "Pop, Jazz, Indie",
      location: "Lahore",
      rating: 4.9,
      avatar: "https://via.placeholder.com/150",
      bio: "Aria Harmony is a renowned singer known for her soulful voice and evocative lyrics.",
      portfolio: "https://example.com/ariaharmony",
      social: { twitter: "#", instagram: "#", facebook: "#", youtube: "#" },
      videos: [
        "https://via.placeholder.com/300x200",
        "https://via.placeholder.com/300x200",
      ],
      sampleTracks: [
        "Harmony in Motion",
        "Echoes of the Soul",
        "Whispers of the Heart",
      ],
    },
    {
      id: 2,
      name: "Jane Smith",
      category: "Band",
      genre: "Rock",
      location: "Karachi",
      rating: 4.8,
      avatar: "https://via.placeholder.com/150",
      bio: "Rock band known for energetic performances.",
      portfolio: "https://example.com/janesmith",
    },
    {
      id: 3,
      name: "DJ Mike",
      category: "DJ",
      genre: "Electronic, House",
      location: "Islamabad",
      rating: 4.7,
      avatar: "https://via.placeholder.com/150",
      bio: "DJ Mike is a popular DJ known for his electrifying performances.",
      portfolio: "https://example.com/djmike",
      social: { twitter: "#", instagram: "#", facebook: "#", youtube: "#" },
      videos: ["https://via.placeholder.com/300x200"],
      sampleTracks: ["Electro Beat", "House Vibes"],
    },
    {
      id: 4,
      name: "Sophia Lee",
      category: "Instrumentalist",
      genre: "Classical",
      location: "Karachi",
      rating: 4.8,
      avatar: "https://via.placeholder.com/150",
      bio: "Sophia is a classical violinist with a passion for timeless melodies.",
      portfolio: "https://example.com/sophialee",
      social: { twitter: "#", instagram: "#", youtube: "#" },
    },
    {
      id: 5,
      name: "David Guetta",
      category: "DJ",
      genre: "House, EDM",
      location: "Islamabad",
      rating: 4.9,
      avatar: "https://via.placeholder.com/150",
      bio: "World-famous DJ known for his energetic beats and hit tracks.",
      portfolio: "https://example.com/davidguetta",
      social: { instagram: "#", facebook: "#", youtube: "#" },
      videos: [
        "https://via.placeholder.com/300x200",
        "https://via.placeholder.com/300x200",
      ],
      sampleTracks: ["Titanium", "Memories"],
    },
    {
      id: 6,
      name: "Ella Fitzgerald",
      category: "Singer",
      genre: "Blues, Jazz",
      location: "Lahore",
      rating: 4.9,
      avatar: "https://via.placeholder.com/150",
      bio: "Ella is known for her smooth voice and deep connection with blues music.",
      portfolio: "https://example.com/ellafitzgerald",
    },
    {
      id: 7,
      name: "Coldplay Tribute Band",
      category: "Band",
      genre: "Alternative Rock",
      location: "Karachi",
      rating: 4.7,
      avatar: "https://via.placeholder.com/150",
      bio: "A tribute band performing Coldplay’s greatest hits.",
      portfolio: "https://example.com/coldplaytribute",
    },
    {
      id: 8,
      name: "Zedd",
      category: "DJ",
      genre: "Electropop",
      location: "Lahore",
      rating: 4.8,
      avatar: "https://via.placeholder.com/150",
      bio: "Zedd is an award-winning DJ known for his captivating electropop tracks.",
      portfolio: "https://example.com/zedd",
      videos: ["https://via.placeholder.com/300x200"],
      sampleTracks: ["Stay", "Clarity"],
    },
    {
      id: 9,
      name: "Yo-Yo Ma",
      category: "Instrumentalist",
      genre: "Classical, Cello",
      location: "Islamabad",
      rating: 5.0,
      avatar: "https://via.placeholder.com/150",
      bio: "Yo-Yo Ma is a world-renowned cellist known for his exceptional performances.",
      portfolio: "https://example.com/yoyoma",
      social: { twitter: "#", youtube: "#", instagram: "#" },
    },
  ];
  
  export default mockArtists;
  